networks:
  web:
    external: true
services:
  web:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    environment:
      - TZ=Europe/Berlin
    volumes:
        - ./httpdocs/:/code
        - ./log:/var/log/nginx/
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
    networks:
      - default
  php:
    restart: always
    image: php:7-fpm
    environment:
      - TZ=Europe/Berlin
      - LANG="de_DE.UTF-8"
      - LANGUAGE="de_DE.de"
      - LC_ALL="de_DE.UTF-8"
    volumes:
        - ./httpdocs/:/code
    networks:
      - default
